In [3]:
!pip install pandas numpy scikit-learn matplotlib joblib streamlit

Requirement already satisfied: pandas in c:\users\leo-k\anaconda7\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\leo-k\anaconda7\lib\site-packages (2.3.5)
Requirement already satisfied: scikit-learn in c:\users\leo-k\anaconda7\lib\site-packages (1.7.2)
Requirement already satisfied: matplotlib in c:\users\leo-k\anaconda7\lib\site-packages (3.10.6)
Requirement already satisfied: joblib in c:\users\leo-k\anaconda7\lib\site-packages (1.5.2)
Requirement already satisfied: streamlit in c:\users\leo-k\anaconda7\lib\site-packages (1.51.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\leo-k\anaconda7\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\leo-k\anaconda7\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\leo-k\anaconda7\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\leo-k\anaconda7\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\leo-k\anaconda7\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\leo-k\anaconda7\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\leo-k\anaconda7\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\leo-k\anaconda7\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\leo-k\anaconda7\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\leo-k\anaconda7\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\leo-k\anaconda7\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\leo-k\anaconda7\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\leo-k\anaconda7\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\leo-k\anaconda7\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\leo-k\anaconda7\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\leo-k\anaconda7\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\leo-k\anaconda7\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\leo-k\anaconda7\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\leo-k\anaconda7\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\leo-k\anaconda7\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\leo-k\anaconda7\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\leo-k\anaconda7\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\leo-k\anaconda7\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: attrs>=22.2.0 in c:\users\leo-k\anaconda7\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\leo-k\anaconda7\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\leo-k\anaconda7\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\leo-k\anaconda7\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\leo-k\anaconda7\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\leo-k\anaconda7\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)

In [4]:
import pandas
print("working")

working

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("dataset.csv")
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [7]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [8]:
df.isnull().sum()

student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [9]:
df = df.dropna()

In [10]:
df.isnull().sum()

student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [15]:
import pandas as pd

df = pd.read_csv("dataset.csv")
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [16]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

In [18]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
print(df.head())

   student_id  weekly_self_study_hours  attendance_percentage  \
0           1                     18.5                   95.6
1           2                     14.0                   80.0
2           3                     19.5                   86.3
3           4                     25.7                   70.2
4           5                     13.4                   81.9

   class_participation  total_score grade
0                  3.8         97.9     A
1                  2.5         83.9     B
2                  5.3        100.0     A
3                  7.0        100.0     A
4                  6.9         92.0     A

In [22]:
print(X_train.shape)
print(y_train.shape)

(800000, 5)
(800000,)

In [23]:
print(X_train.shape)
print(y_train.shape)

(800000, 5)
(800000,)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
model = LogisticRegression()
print("Model created")

Model created

In [28]:
model.fit(X_train, y_train)
print("Training done")

Training done

C:\Users\LEO-k\anaconda7\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [30]:
y_pred = model.predict(X_test)
print(y_pred[:10])

['D' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A']

In [31]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.638945

In [32]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[108515   1373      0      0      0]
 [ 32978  17380      0   1198      0]
 [  3812  21210    451   2907      0]
 [    41   6645    798   1443      0]
 [     0    723    273    253      0]]

In [33]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

C:\Users\LEO-k\anaconda7\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\LEO-k\anaconda7\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score   support

           A       0.75      0.99      0.85    109888
           B       0.37      0.34      0.35     51556
           C       0.30      0.02      0.03     28380
           D       0.25      0.16      0.20      8927
           F       0.00      0.00      0.00      1249

    accuracy                           0.64    200000
   macro avg       0.33      0.30      0.29    200000
weighted avg       0.56      0.64      0.57    200000

C:\Users\LEO-k\anaconda7\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [34]:
import joblib

In [35]:
joblib.dump(model, "best_model.pkl")
print("Model saved")

Model saved